version: '3.8'
services:
  app:
    image: 'node:14.5'
    container_name: NestApp
    external_links:
      - db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    user: 'node'
    working_dir: /app
    environment:
      - MONGO_DB=dev-camps
      - HOST=mongo
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    tty: true
    command: 'npm run start'
  db:
    image: mongo
    container_name: mongo
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'
volumes:
  data:
